//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace MobileSrc.Commuter.Shared.RouteServices {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1", IsNullable=true)]
    public partial class Response {
        
        private string copyrightField;
        
        private string brandLogoUriField;
        
        private int statusCodeField;
        
        private string statusDescriptionField;
        
        private AuthenticationResultCode authenticationResultCodeField;
        
        private string[] errorDetailsField;
        
        private string traceIdField;
        
        private ResourceSet[] resourceSetsField;
        
        /// <remarks/>
        public string Copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        public string BrandLogoUri {
            get {
                return this.brandLogoUriField;
            }
            set {
                this.brandLogoUriField = value;
            }
        }
        
        /// <remarks/>
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public AuthenticationResultCode AuthenticationResultCode {
            get {
                return this.authenticationResultCodeField;
            }
            set {
                this.authenticationResultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string[] ErrorDetails {
            get {
                return this.errorDetailsField;
            }
            set {
                this.errorDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string TraceId {
            get {
                return this.traceIdField;
            }
            set {
                this.traceIdField = value;
            }
        }
        
        /// <remarks/>
        public ResourceSet[] ResourceSets {
            get {
                return this.resourceSetsField;
            }
            set {
                this.resourceSetsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public enum AuthenticationResultCode {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        NoCredentials,
        
        /// <remarks/>
        ValidCredentials,
        
        /// <remarks/>
        InvalidCredentials,
        
        /// <remarks/>
        CredentialsExpired,
        
        /// <remarks/>
        NotAuthorized,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class ResourceSet {
        
        private long estimatedTotalField;
        
        private Resource[] resourcesField;
        
        /// <remarks/>
        public long EstimatedTotal {
            get {
                return this.estimatedTotalField;
            }
            set {
                this.estimatedTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(BirdseyeMetadata))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(DataflowJob))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(ImageryMetadata))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(Location))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(Route))]
        public Resource[] Resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class BirdseyeMetadata : ImageryMetadata {
        
        private double orientationField;
        
        private int tilesXField;
        
        private int tilesYField;
        
        /// <remarks/>
        public double Orientation {
            get {
                return this.orientationField;
            }
            set {
                this.orientationField = value;
            }
        }
        
        /// <remarks/>
        public int TilesX {
            get {
                return this.tilesXField;
            }
            set {
                this.tilesXField = value;
            }
        }
        
        /// <remarks/>
        public int TilesY {
            get {
                return this.tilesYField;
            }
            set {
                this.tilesYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BirdseyeMetadata))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class ImageryMetadata : Resource {
        
        private string imageUrlField;
        
        private string[] imageUrlSubdomainsField;
        
        private int imageWidthField;
        
        private int imageHeightField;
        
        private int zoomMinField;
        
        private int zoomMaxField;
        
        private string vintageStartField;
        
        private string vintageEndField;
        
        private ImageryProvider[] imageryProviderField;
        
        /// <remarks/>
        public string ImageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string[] ImageUrlSubdomains {
            get {
                return this.imageUrlSubdomainsField;
            }
            set {
                this.imageUrlSubdomainsField = value;
            }
        }
        
        /// <remarks/>
        public int ImageWidth {
            get {
                return this.imageWidthField;
            }
            set {
                this.imageWidthField = value;
            }
        }
        
        /// <remarks/>
        public int ImageHeight {
            get {
                return this.imageHeightField;
            }
            set {
                this.imageHeightField = value;
            }
        }
        
        /// <remarks/>
        public int ZoomMin {
            get {
                return this.zoomMinField;
            }
            set {
                this.zoomMinField = value;
            }
        }
        
        /// <remarks/>
        public int ZoomMax {
            get {
                return this.zoomMaxField;
            }
            set {
                this.zoomMaxField = value;
            }
        }
        
        /// <remarks/>
        public string VintageStart {
            get {
                return this.vintageStartField;
            }
            set {
                this.vintageStartField = value;
            }
        }
        
        /// <remarks/>
        public string VintageEnd {
            get {
                return this.vintageEndField;
            }
            set {
                this.vintageEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImageryProvider")]
        public ImageryProvider[] ImageryProvider {
            get {
                return this.imageryProviderField;
            }
            set {
                this.imageryProviderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class ImageryProvider {
        
        private string attributionField;
        
        private CoverageArea[] coverageAreaField;
        
        /// <remarks/>
        public string Attribution {
            get {
                return this.attributionField;
            }
            set {
                this.attributionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CoverageArea")]
        public CoverageArea[] CoverageArea {
            get {
                return this.coverageAreaField;
            }
            set {
                this.coverageAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class CoverageArea {
        
        private int zoomMinField;
        
        private int zoomMaxField;
        
        private BoundingBox boundingBoxField;
        
        /// <remarks/>
        public int ZoomMin {
            get {
                return this.zoomMinField;
            }
            set {
                this.zoomMinField = value;
            }
        }
        
        /// <remarks/>
        public int ZoomMax {
            get {
                return this.zoomMaxField;
            }
            set {
                this.zoomMaxField = value;
            }
        }
        
        /// <remarks/>
        public BoundingBox BoundingBox {
            get {
                return this.boundingBoxField;
            }
            set {
                this.boundingBoxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class BoundingBox {
        
        private double southLatitudeField;
        
        private double westLongitudeField;
        
        private double northLatitudeField;
        
        private double eastLongitudeField;
        
        /// <remarks/>
        public double SouthLatitude {
            get {
                return this.southLatitudeField;
            }
            set {
                this.southLatitudeField = value;
            }
        }
        
        /// <remarks/>
        public double WestLongitude {
            get {
                return this.westLongitudeField;
            }
            set {
                this.westLongitudeField = value;
            }
        }
        
        /// <remarks/>
        public double NorthLatitude {
            get {
                return this.northLatitudeField;
            }
            set {
                this.northLatitudeField = value;
            }
        }
        
        /// <remarks/>
        public double EastLongitude {
            get {
                return this.eastLongitudeField;
            }
            set {
                this.eastLongitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class RoutePath {
        
        private Line lineField;
        
        /// <remarks/>
        public Line Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class Line : Shape {
        
        private Point[] pointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Point")]
        public Point[] Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class Point : Shape {
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Point))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Line))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public abstract partial class Shape {
        
        private double[] boundingBoxField;
        
        /// <remarks/>
        public double[] BoundingBox {
            get {
                return this.boundingBoxField;
            }
            set {
                this.boundingBoxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class Warning {
        
        private string warningTypeField;
        
        private string severityField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string warningType {
            get {
                return this.warningTypeField;
            }
            set {
                this.warningTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class Hint {
        
        private string hintTypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hintType {
            get {
                return this.hintTypeField;
            }
            set {
                this.hintTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class Instruction {
        
        private string maneuverTypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maneuverType {
            get {
                return this.maneuverTypeField;
            }
            set {
                this.maneuverTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class ItineraryItem {
        
        private string travelModeField;
        
        private double travelDistanceField;
        
        private long travelDurationField;
        
        private Point maneuverPointField;
        
        private Instruction instructionField;
        
        private string compassDirectionField;
        
        private Hint[] hintField;
        
        private Warning[] warningField;
        
        /// <remarks/>
        public string TravelMode {
            get {
                return this.travelModeField;
            }
            set {
                this.travelModeField = value;
            }
        }
        
        /// <remarks/>
        public double TravelDistance {
            get {
                return this.travelDistanceField;
            }
            set {
                this.travelDistanceField = value;
            }
        }
        
        /// <remarks/>
        public long TravelDuration {
            get {
                return this.travelDurationField;
            }
            set {
                this.travelDurationField = value;
            }
        }
        
        /// <remarks/>
        public Point ManeuverPoint {
            get {
                return this.maneuverPointField;
            }
            set {
                this.maneuverPointField = value;
            }
        }
        
        /// <remarks/>
        public Instruction Instruction {
            get {
                return this.instructionField;
            }
            set {
                this.instructionField = value;
            }
        }
        
        /// <remarks/>
        public string CompassDirection {
            get {
                return this.compassDirectionField;
            }
            set {
                this.compassDirectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Hint")]
        public Hint[] Hint {
            get {
                return this.hintField;
            }
            set {
                this.hintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Warning")]
        public Warning[] Warning {
            get {
                return this.warningField;
            }
            set {
                this.warningField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class Address {
        
        private string addressLineField;
        
        private string adminDistrictField;
        
        private string adminDistrict2Field;
        
        private string countryRegionField;
        
        private string formattedAddressField;
        
        private string localityField;
        
        private string postalCodeField;
        
        /// <remarks/>
        public string AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
            }
        }
        
        /// <remarks/>
        public string AdminDistrict {
            get {
                return this.adminDistrictField;
            }
            set {
                this.adminDistrictField = value;
            }
        }
        
        /// <remarks/>
        public string AdminDistrict2 {
            get {
                return this.adminDistrict2Field;
            }
            set {
                this.adminDistrict2Field = value;
            }
        }
        
        /// <remarks/>
        public string CountryRegion {
            get {
                return this.countryRegionField;
            }
            set {
                this.countryRegionField = value;
            }
        }
        
        /// <remarks/>
        public string FormattedAddress {
            get {
                return this.formattedAddressField;
            }
            set {
                this.formattedAddressField = value;
            }
        }
        
        /// <remarks/>
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class RouteLeg {
        
        private double travelDistanceField;
        
        private long travelDurationField;
        
        private Point actualStartField;
        
        private Point actualEndField;
        
        private Location startLocationField;
        
        private Location endLocationField;
        
        private ItineraryItem[] itineraryItemField;
        
        /// <remarks/>
        public double TravelDistance {
            get {
                return this.travelDistanceField;
            }
            set {
                this.travelDistanceField = value;
            }
        }
        
        /// <remarks/>
        public long TravelDuration {
            get {
                return this.travelDurationField;
            }
            set {
                this.travelDurationField = value;
            }
        }
        
        /// <remarks/>
        public Point ActualStart {
            get {
                return this.actualStartField;
            }
            set {
                this.actualStartField = value;
            }
        }
        
        /// <remarks/>
        public Point ActualEnd {
            get {
                return this.actualEndField;
            }
            set {
                this.actualEndField = value;
            }
        }
        
        /// <remarks/>
        public Location StartLocation {
            get {
                return this.startLocationField;
            }
            set {
                this.startLocationField = value;
            }
        }
        
        /// <remarks/>
        public Location EndLocation {
            get {
                return this.endLocationField;
            }
            set {
                this.endLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItineraryItem")]
        public ItineraryItem[] ItineraryItem {
            get {
                return this.itineraryItemField;
            }
            set {
                this.itineraryItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class Location : Resource {
        
        private string entityTypeField;
        
        private Address addressField;
        
        private Confidence confidenceField;
        
        /// <remarks/>
        public string EntityType {
            get {
                return this.entityTypeField;
            }
            set {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public Confidence Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public enum Confidence {
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataflowJob))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImageryMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BirdseyeMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Location))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Route))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class Resource {
        
        private string nameField;
        
        private string idField;
        
        private Link[] linkField;
        
        private Point pointField;
        
        private BoundingBox boundingBoxField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Link")]
        public Link[] Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public Point Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        public BoundingBox BoundingBox {
            get {
                return this.boundingBoxField;
            }
            set {
                this.boundingBoxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class Link {
        
        private string roleField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class DataflowJob : Resource {
        
        private string descriptionField;
        
        private string statusField;
        
        private string errorMessageField;
        
        private System.DateTime createdDateField;
        
        private System.Nullable<System.DateTime> completedDateField;
        
        private long totalEntityCountField;
        
        private long processedEntityCountField;
        
        private long failedEntityCountField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CompletedDate {
            get {
                return this.completedDateField;
            }
            set {
                this.completedDateField = value;
            }
        }
        
        /// <remarks/>
        public long TotalEntityCount {
            get {
                return this.totalEntityCountField;
            }
            set {
                this.totalEntityCountField = value;
            }
        }
        
        /// <remarks/>
        public long ProcessedEntityCount {
            get {
                return this.processedEntityCountField;
            }
            set {
                this.processedEntityCountField = value;
            }
        }
        
        /// <remarks/>
        public long FailedEntityCount {
            get {
                return this.failedEntityCountField;
            }
            set {
                this.failedEntityCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/search/local/ws/rest/v1")]
    public partial class Route : Resource {
        
        private string distanceUnitField;
        
        private string durationUnitField;
        
        private double travelDistanceField;
        
        private long travelDurationField;
        
        private RouteLeg[] routeLegField;
        
        private RoutePath routePathField;
        
        /// <remarks/>
        public string DistanceUnit {
            get {
                return this.distanceUnitField;
            }
            set {
                this.distanceUnitField = value;
            }
        }
        
        /// <remarks/>
        public string DurationUnit {
            get {
                return this.durationUnitField;
            }
            set {
                this.durationUnitField = value;
            }
        }
        
        /// <remarks/>
        public double TravelDistance {
            get {
                return this.travelDistanceField;
            }
            set {
                this.travelDistanceField = value;
            }
        }
        
        /// <remarks/>
        public long TravelDuration {
            get {
                return this.travelDurationField;
            }
            set {
                this.travelDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RouteLeg")]
        public RouteLeg[] RouteLeg {
            get {
                return this.routeLegField;
            }
            set {
                this.routeLegField = value;
            }
        }
        
        /// <remarks/>
        public RoutePath RoutePath {
            get {
                return this.routePathField;
            }
            set {
                this.routePathField = value;
            }
        }
    }
}
